version: '3'
services:
  adaptive-cloud-service:
    image: 10.10.102.198:5500/gczx/dev_api:release
    ports:
      - 8414:8414
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.HOSTNAME == gcjk01-app-docker02
