# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  skip-dirs:
    - vendor$

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - goconst
    - gocritic
    - golint
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  fast: true

# all available settings of specific linters
linters-settings:
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8